book_homepage:
    path:     /
    defaults: { _controller: "BookBundle:Book:main" }

book_change:
    resource: "@BookBundle/Resources/config/routing/book.yml"
    prefix: /books

api_book:
    resource: "@BookBundle/Resources/config/routing/api.yml"
    prefix: /api

book_document:
    path: /uploads/books/{id}
    defaults: { _controller: "BookBundle:Book:document"}
    methods: GET

book_image:
    path: /uploads/titles/{id}
    defaults: { _controller: "BookBundle:Book:image"}
    methods: GET

download_titles:
    path: /downloads/titles/{id}
    defaults: { _controller: "BookBundle:Book:downloadTitle" }
    methods: GET

download_books:
    path: /downloads/books/{id}
    defaults: { _controller: "BookBundle:Book:downloadBook" }
    methods: