book_index:
    path: /
    defaults: { _controller: "BookBundle:Book:index" }
    methods: GET

book_new:
    path: /add
    defaults: { _controller: "BookBundle:Book:add" }
    methods: [GET, POST]

book_edit:
    path: /{id}/edit
    defaults: { _controller: "BookBundle:Book:edit" }
    methods: [GET, POST]

book_delete:
    path: /{id}/delete
    defaults: { _controller: "BookBundle:Book:delete" }
    methods: DELETE
